"""
POST /export/pdf — generate a downloadable Legal Advisory Report PDF.
"""
import io
import logging
from datetime import datetime
from typing import Any, Dict, List, Optional

from fastapi import APIRouter, Depends
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/export", tags=["export"])


class ExportRequest(BaseModel):
    query: str
    summary: str
    citations: List[Dict[str, Any]] = []
    domain: Optional[str] = None
    metadata: Dict[str, Any] = {}


def _build_pdf(req: ExportRequest) -> bytes:
    from fpdf import FPDF

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # --- Header ---
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(30, 30, 80)
    pdf.cell(0, 12, "Legal Advisory Report", ln=True, align="C")

    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 6, f"Generated: {datetime.now().strftime('%d %B %Y, %H:%M')}", ln=True, align="C")
    if req.domain:
        pdf.cell(0, 6, f"Domain: {req.domain}", ln=True, align="C")
    pdf.ln(6)

    pdf.set_draw_color(200, 200, 220)
    pdf.set_line_width(0.4)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)

    # --- Query ---
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(30, 30, 80)
    pdf.cell(0, 8, "Query", ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(50, 50, 50)
    pdf.set_fill_color(245, 245, 250)
    pdf.multi_cell(0, 6, req.query, fill=True)
    pdf.ln(5)

    # --- Answer ---
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(30, 30, 80)
    pdf.cell(0, 8, "Legal Advisory", ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(50, 50, 50)

    # Write summary paragraph by paragraph
    for para in req.summary.split("\n"):
        para = para.strip()
        if not para:
            pdf.ln(3)
            continue
        pdf.multi_cell(0, 6, para)
    pdf.ln(5)

    # --- Citations ---
    if req.citations:
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(4)
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(30, 30, 80)
        pdf.cell(0, 8, "Sources", ln=True)

        seen = set()
        for c in req.citations:
            fname = c.get("filename", "unknown")
            page = c.get("page", "?")
            excerpt = c.get("excerpt", "")[:100]
            key = f"{fname}:{page}"
            if key in seen:
                continue
            seen.add(key)
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(60, 60, 140)
            pdf.cell(0, 5, f"{fname}  —  Page {page}", ln=True)
            if excerpt:
                pdf.set_font("Helvetica", "I", 8)
                pdf.set_text_color(100, 100, 100)
                pdf.multi_cell(0, 4, f'"{excerpt}…"')
            pdf.ln(2)

    # --- Footer ---
    pdf.ln(6)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(140, 140, 140)
    pdf.multi_cell(
        0, 4,
        "Disclaimer: This report is generated by an AI system and is for "
        "informational and educational purposes only. It does not constitute "
        "formal legal advice. Please consult a qualified legal professional "
        "for advice specific to your situation.",
    )

    return pdf.output()


@router.post("/pdf")
async def export_pdf(request: ExportRequest):
    """Generate and return a formatted PDF of the legal advisory response."""
    pdf_bytes = _build_pdf(request)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"legal_advisory_{timestamp}.pdf"
    return StreamingResponse(
        io.BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename={filename}"},
    )
